steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/sanjay3889/cicd-service.git', 'myrepo']

  # Step 2: Execute SQL script in BigQuery
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'bq'
      - 'query'
      - '--use_legacy_sql=false'
      - '--project_id=qwiklabs-gcp-03-19de5989b72a'
      - '--format=none'
      - '$(cat myrepo/missing.sql)'

options:
  logging: CLOUD_LOGGING_ONLY
