steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/sanjay3889/cicd-service.git', 'myrepo']

  # Step 2: Execute SQL script in BigQuery using input redirection
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get project_id from the build substitution
        PROJECT_ID="${_PROJECT_ID}"
        
        # Ensure project_id is provided
        if [ -z "$PROJECT_ID" ]; then
          echo "Error: PROJECT_ID is required."
          exit 1
        fi

        
        echo "Running query on project: $PROJECT_ID"
        
        # Run the BigQuery query using input redirection
        bq query --use_legacy_sql=false --project_id="$PROJECT_ID" --format=none < myrepo/missing.sql

options:
  logging: CLOUD_LOGGING_ONLY
