steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/sanjay3889/cicd-service.git', 'myrepo']


  # Step 2: Execute SQL script in BigQuery using input redirection
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Ensure project_id is quoted properly
        PROJECT_ID="qwiklabs-gcp-00-bdf5952fd1f3"
        echo "Running query on project: $PROJECT_ID"
        # Run the bq query using input redirection to pass the SQL content
        bq query --use_legacy_sql=false --format=none < myrepo/missing.sql

options:
  logging: CLOUD_LOGGING_ONLY
