steps:
# Step 1: Clone the GitHub repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sanjay3889/cicd-service.git', '.']

# Step 3: Execute SQL script in BigQuery
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'bq'
  - 'query'
  - '--use_legacy_sql=false'
  - '--project=qwiklabs-gcp-04-ee6c0d22a945'
  - '--format=none'
  - '$(cat missing.sql)'

