- name: 'gcr.io/cloud-builders/git'
  args: ['clone','https://github.com/sanjay3889/cicd-service.git']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'bq'
  - 'query'
  - '--use_legacy_sql=false'
  - '--project=qwiklabs-gcp-04-ee6c0d22a945'
  - '--format=none'
  - '$(cat missing.sql)'
  
