steps:
# Step 1: Clone the GitHub repository
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/sanjay3889/cicd-service.git', 'myrepo']

# Step 2: Change to the cloned repository directory
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', 'cd myrepo']

# Step 3: Authenticate to BigQuery
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'application-default', 'login']

# Step 4: Execute SQL script in BigQuery
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'bq'
  - 'query'
  - '--use_legacy_sql=false'
  - '--project=qwiklabs-gcp-04-ee6c0d22a945'
  - '--format=none'
  - '$(cat myrepo/missing.sql)'

# Specify the logging option
options:
  logging: CLOUD_LOGGING_ONLY
